<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="b71d37b539cd" failures="1" tests="3" name="user-mike" time="6.004" errors="0" timestamp="2024-10-02T05:12:53 GMT">
  <testcase classname="org.automation.tests.vendorportal.VendorPortalTest" name="loginTest" time="1.12"/>
  <testcase classname="org.automation.tests.vendorportal.VendorPortalTest" name="dashboardTest" time="2.867">
    <failure type="java.lang.AssertionError" message="expected [8] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [8] but found [10]
at org.automation.tests.vendorportal.VendorPortalTest.dashboardTest(VendorPortalTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- dashboardTest -->
  <testcase classname="org.automation.tests.vendorportal.VendorPortalTest" name="logoutTest" time="0.0">
    <skipped/>
  </testcase> <!-- logoutTest -->
</testsuite> <!-- user-mike -->
